version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb_server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
