apiVersion: v1
kind: Service
metadata:
  name: svc-produto-api
spec:
  selector:
    app: pod-produto-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081
  type: LoadBalancer